FROM python:3.12.4

WORKDIR /home

COPY . .

RUN apt update
RUN pip install -r requirements.txt
RUN apt install -y ffmpeg
RUN apt install -y proxychains4
RUN apt install -y libpulse-dev
RUN apt install -y libasound2

COPY bin/songrec /usr/bin
RUN ["chmod", "+x", "/usr/bin/songrec"]

CMD ["gunicorn", "media-service.main:main", "--bind", "0.0.0.0:8050", "--worker-class", "aiohttp.GunicornWebWorker", "--workers", "24"]