FROM python:3.12.4

WORKDIR /home4

ENV PYTHONUNBUFFERED=1


COPY requirements.txt .

RUN pip install -r requirements.txt


RUN apt update
RUN apt install -y ffmpeg proxychains4 libpulse-dev libasound2

COPY . .

COPY bin/songrec /usr/bin
RUN chmod +x /usr/bin/songrec



CMD ["gunicorn", "media-service.main:main", "--bind", "0.0.0.0:8050", "--worker-class", "aiohttp.GunicornWebWorker", "--reload"]
